<a href="https://colab.research.google.com/github/kaz-kobayashi/2019TUSjikkenC/blob/master/190621_linearprogramming.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pulp

     |████████████████████████████████| 13.6MB 4.4MB/s 
  Stored in directory: /root/.cache/pip/wheels/5e/76/77/e28b22219e46e3b4b033f02e8b36b2770ae545bdcf60c2b224
Successfully built pulp


In [0]:
from pulp import *

In [0]:
Area,School=[1,2,3,4,5,6],[1,2,3]

In [0]:
x=LpVariable.dicts("x",(Area,School),0,10000,'Integer')
s=LpVariable.dicts("s",(Area,School),0,10000,'Integer')
e=LpVariable.dicts("e",(Area,School),0,10000,'Integer')

In [32]:
x[1][2]

x_1_2

In [55]:
prob=LpProblem(name="SA",sense=LpMinimize)
p=""
for i in Area:
    for j in School:
      p+=C[i-1][j-1]*(x[i][j]+s[i][j]+e[i][j])
prob+=p
#xvar=[x[1][i] for i in x[1]]
#print(C[0]*xvar)
print(prob)

SA:
MINIMIZE
300*e_1_1 + 700*e_1_3 + 400*e_2_2 + 500*e_2_3 + 600*e_3_1 + 300*e_3_2 + 200*e_3_3 + 200*e_4_1 + 500*e_4_2 + 400*e_5_3 + 500*e_6_1 + 300*e_6_2 + 300*s_1_1 + 700*s_1_3 + 400*s_2_2 + 500*s_2_3 + 600*s_3_1 + 300*s_3_2 + 200*s_3_3 + 200*s_4_1 + 500*s_4_2 + 400*s_5_3 + 500*s_6_1 + 300*s_6_2 + 300*x_1_1 + 700*x_1_3 + 400*x_2_2 + 500*x_2_3 + 600*x_3_1 + 300*x_3_2 + 200*x_3_3 + 200*x_4_1 + 500*x_4_2 + 400*x_5_3 + 500*x_6_1 + 300*x_6_2 + 0
VARIABLES
0 <= e_1_1 <= 10000 Integer
0 <= e_1_3 <= 10000 Integer
0 <= e_2_2 <= 10000 Integer
0 <= e_2_3 <= 10000 Integer
0 <= e_3_1 <= 10000 Integer
0 <= e_3_2 <= 10000 Integer
0 <= e_3_3 <= 10000 Integer
0 <= e_4_1 <= 10000 Integer
0 <= e_4_2 <= 10000 Integer
0 <= e_5_3 <= 10000 Integer
0 <= e_6_1 <= 10000 Integer
0 <= e_6_2 <= 10000 Integer
0 <= s_1_1 <= 10000 Integer
0 <= s_1_3 <= 10000 Integer
0 <= s_2_2 <= 10000 Integer
0 <= s_2_3 <= 10000 Integer
0 <= s_3_1 <= 10000 Integer
0 <= s_3_2 <= 10000 Integer
0 <= s_3_3 <= 10000 Integer
0 <= s_4_1 

In [42]:
print(C[1])
print(x[1])

[  0 400 500]
{1: x_1_1, 2: x_1_2, 3: x_1_3}


In [0]:
import numpy as np

In [0]:
C=np.array([\
            [300,0,700],\
            [0,400,500],\
            [600,300,200],\
            [200,500,0],\
            [0,0,400],\
            [500,300,0]\
           ])

In [0]:
prob=LpProblem(name='SA',sense=LpMinimize)

In [27]:
print(C)

[[300   0 700]
 [  0 400 500]
 [600 300 200]
 [200 500   0]
 [  0   0 400]
 [500 300   0]]


In [57]:
x.keys()
for i in [1,2,3,4,5,6]:
    print(i,x[i])

1 {1: x_1_1, 2: x_1_2, 3: x_1_3}
2 {1: x_2_1, 2: x_2_2, 3: x_2_3}
3 {1: x_3_1, 2: x_3_2, 3: x_3_3}
4 {1: x_4_1, 2: x_4_2, 3: x_4_3}
5 {1: x_5_1, 2: x_5_2, 3: x_5_3}
6 {1: x_6_1, 2: x_6_2, 3: x_6_3}


In [0]:
capa=[900,1100,1000]
prob=LpProblem(name='SA',sense=LpMinimize)
sum1=""
for k in School:
    sum1=""
    for i in Area:
        sum1+=x[i][k]+s[i][k]+e[i][k]
    prob+=sum1<=capa[k-1]


In [0]:
print(prob)

In [0]:
p=""
xcard=[144,222,165,98,195,153]
scard=[171,168,176,140,170,126]
ecard=[135,210,209,112,135,171]
for i in Area:
    prob+=lpSum([ x[i][j] for j in School] )==xcard[i-1]
    prob+=lpSum([ s[i][j] for j in School] )==scard[i-1]
    prob+=lpSum([ e[i][j] for j in School] )==ecard[i-1]

In [0]:
print(prob)

In [83]:
sum1,sum2,sum3="","",""
ssum=["","",""]
for j in range(3):
    for i in range(6):
        sum1+=x[i+1][1]
        sum1+=s[i+1][1]
        sum1+=e[i+1][1]
for i in range(6):
    sum2+=x[i+1][2]
    sum2+=s[i+1][2]
    sum2+=e[i+1][2]
for i in range(6):
    sum3+=x[i+1][3]
    sum3+=s[i+1][3]
    sum3+=e[i+1][3]    
ssum=[sum1,sum2,sum3]

print(ssum)
    

[1*e_1_1 + 1*e_2_1 + 1*e_3_1 + 1*e_4_1 + 1*e_5_1 + 1*e_6_1 + 1*s_1_1 + 1*s_2_1 + 1*s_3_1 + 1*s_4_1 + 1*s_5_1 + 1*s_6_1 + 1*x_1_1 + 1*x_2_1 + 1*x_3_1 + 1*x_4_1 + 1*x_5_1 + 1*x_6_1 + 0, 1*e_1_2 + 1*e_2_2 + 1*e_3_2 + 1*e_4_2 + 1*e_5_2 + 1*e_6_2 + 1*s_1_2 + 1*s_2_2 + 1*s_3_2 + 1*s_4_2 + 1*s_5_2 + 1*s_6_2 + 1*x_1_2 + 1*x_2_2 + 1*x_3_2 + 1*x_4_2 + 1*x_5_2 + 1*x_6_2 + 0, 1*e_1_3 + 1*e_2_3 + 1*e_3_3 + 1*e_4_3 + 1*e_5_3 + 1*e_6_3 + 1*s_1_3 + 1*s_2_3 + 1*s_3_3 + 1*s_4_3 + 1*s_5_3 + 1*s_6_3 + 1*x_1_3 + 1*x_2_3 + 1*x_3_3 + 1*x_4_3 + 1*x_5_3 + 1*x_6_3 + 0]
